===============================
Test for 101-lazy_matrix_mul.py 
-------------------------------

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> lazy_matrix_mul([[1, 2], [4, 5], [7, 8]], [[1, 2, 3], [0, 5, 2]])
array([[ 1, 12,  7],
       [ 4, 33, 22],
       [ 7, 54, 37]])

>>> lazy_matrix_mul([[1, 2], [-4, 5]], [[1, 2.5, 3], [0, 5, 2]])
array([[ 1. , 12.5,  7. ],
       [-4. , 15. , -2. ]])

>>> lazy_matrix_mul([[1, 2], [-4, 5]], 4)
array([[  4,   8],
       [-16,  20]])

>>> lazy_matrix_mul("Hello", [[4, 2]])
Traceback (most recent call last):
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U5') dtype('<U5') dtype('<U5')

>>> lazy_matrix_mul([], [[4, 2]])
Traceback (most recent call last):
ValueError: shapes (0,) and (1,2) not aligned: 0 (dim 0) != 1 (dim 0)

>>> lazy_matrix_mul([[]], [[4, 2]])
Traceback (most recent call last):
ValueError: shapes (1,0) and (1,2) not aligned: 0 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[1, 3]], [])
Traceback (most recent call last):
ValueError: shapes (1,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0)

>>> lazy_matrix_mul([[1, 3]], [[]])
Traceback (most recent call last):
ValueError: shapes (1,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[4, 2]], [[4, "5"]])
Traceback (most recent call last):
ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[4, 2]], [["Holberton", 5]])
Traceback (most recent call last):
ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[4, True]], [[33, 5]])
Traceback (most recent call last):
ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([["School"], [3 ,5]], [[33, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence

>>> lazy_matrix_mul([[1, 2, 2], [3, 1]], [[33, 5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2, 2], [3, 1, 4]], [[33, 5], [5]])
Traceback (most recent call last):
ValueError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2, 2], [3, 1, 3]], [[33, 5]])
Traceback (most recent call last):
ValueError: shapes (2,3) and (1,2) not aligned: 3 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[1, 2], [1, 3]], [[33, 5], [0, 5], [3 , 33]])
Traceback (most recent call last):
ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

